Repository OpenVoiceOS/ovos_skill_manager, pull requests merged in 2021-08, with the labels that each got.

#52 detect skill folder
  ovos_skills_manager/commands.py
  ovos_skills_manager/skill_entry.py
  setup.py
Labels: bug, severe

#56 add bus event
  ovos_skills_manager/osm.py
  setup.py
Labels: enhancement

#57 fix install from url
  ovos_skills_manager/osm.py
  setup.py
Labels: bug
